### PR TITLE
Merge some changes from djs55/refactor-modules

### PR DESCRIPTION
**Pull request by talex5**
The djs55/refactor-modules branch was started last year to make various changes:

* Support netback (not just netfront)
* Clean up the code
* Be stricter about checking messages
* Use a functor over events and memory types
* Improve the public API

With all these changes, and being incomplete, it was hard to review, and master has now moved on. This PR merges some of the changes from this branch to make review easier.

- It brings in `Flag`, `RX`, `TX` and `ResultM` (which now uses the new `result` type instead of a custom one).
    
- Now we only need to disable unused value warnings in the protocol files. Other files are compiled with all warnings on. Removed all unused code that this discovered.

- I also updated it to use the new `Cstruct.fillv`.

My longer term goal is to get netback support added to master, but currently the public API is unchanged (netfront only). The behaviour should be unchanged too, except that it may be more fussy about invalid flags and offsets.

### CODE REVIEW

**Comment by talex5** [comment]
I've now also added `Xenstore`, `Features` and `S` modules from `djs55/refactor-modules`. This means that `Frontend` no longer uses `XenStore` directly.

Notes:

- The original branch tried to read `{backend}/frontend-id`.
  This wasn't used for anything and on Qubes we don't have permission to
  read it anyway.

- The original branch changed `request-rx-copy` to `feature-rx-copy`.
  I think this was by accident. Linux's netback expects `request` from
  the frontend, but writes `feature-rx-copy` to the backend config.

- The branch changed `OS.Device_state.Connected` to the string `"4"`.
  This was probably unintentional, so staying with the symbolic name.

- I also expanded this to a match. The code previous would retry for
  the `Closed` and `Reconfigured` states - I've left the old behaviour but
  possibly this is wrong.

- The branch's `write_features` tried to nest an `Xs.immediate` inside a
  transaction, which caused it to retry endlessly.

- ```frontend (`Server _)``` tried to read the "backend" key. I think it
  should have been "frontend", so changed it.

**Comment by talex5** [comment]
Some more bits from @djs55's branch, plus some cleanups:

- I brought back `frontend_id`, as it's needed for netback. If we are the frontend, I now get this from `domid`, which we do have permission to read.

- Some paths ended up with `//` in them. I added a `(/)` operator to join Xenstore paths safely.

- `write_backend` is now `init_backend`, and now also sets the state to `InitWait`, which the protocol requires.

- `Frontend` now uses the new `Stats` module (but I changed its types to match the existing Mirage ones).

- Frontend wasn't handling the case of a frame split over multiple responses, so I added a `Recv_buffer` module to join them. This will also be useful for the backend.
    
- The frontend also now uses the `offset` field in responses, though it always seems to be zero in practice.

- `RX.Response.status` is now an enum, to make it clear that this may hold either a size or an error code.

- `listen` now starts and returns the polling thread. Before, it returned a dummy thread that never resolved. This means that errors in the listen thread should now be reported.
    
- Errors in the user function are now handled by `Lwt.async` (however that is configured). Before, we always printed the exception and then continued.
    
- Another change is that we previously started listening immediately but discarded all packets until listen was called. It's not clear why we wanted to do that (though a comment indicated it was the intended behaviour). Not dropping packets seems like a more useful behaviour and simplifies the code. The user can always supply a function that drops packets if they want that.

- I also tried changing the representation of flags from a list to an abstract set (actually just an int). Using a list here felt a bit wasteful. This means we can now represent unknown flags again. On the other hand, the sexp serialisation is now just an int rather than a human-readable list of flags.

**Comment by talex5** [comment]
After reading the Linux source code, I've made some changes to how we handle fragmented packets. The logic is that the first request contains the total size and the remaining ones give their own sizes. You have to subtract the sizes of all the following requests to find the size of the first.

I've also added in the backend implementation, with a few changes:

- Removed functorisation, as required libraries not released yet.
- Added locking.
- Added support for writing messages larger than a page.
- Added code to handle fragmented frames and to reply to requests.
- Don't limit size field in messages; it can be more than one page.

I tested it using two unikernels under Qubes. One sends frames of various sizes (some larger than a page) to the other, which echos them back. The sender confirms it got the same data back.

There are some improvements that should be made at some point:

- The backend should be robust about freeing resources when the client disconnects.
- There should be some back-pressure mechanism if the client is sending too fast.
- Disconnect isn't implemented.

However, similar issues also affect the existing frontend, so maybe they shouldn't block it being merged.

@djs55 - would be good if you can find time to review this...

**Comment by djs55** [comment]
After a review with @talex5, decided to merge this!

**Pull request merged**
