### PR TITLE
fix request structure

### PR DESCRIPTION
**Pull request by palainp**
Fix a issue spotted with qubes-mirage-firewall (in https://github.com/mirage/qubes-mirage-firewall/pull/193).

### CODE REVIEW

**Comment by hannesm** [comment]
Thanks, I just prepared an identical commit :)

**Comment by palainp** [comment]
I'm lucky luke :)

**Comment by hannesm** [comment]
I opened https://github.com/ocaml/opam-repository/pull/25822 so that there won't be many people suffering from the bad release.

**Comment by hannesm** [comment]
thanks, merged and released 2.1.5 to opam-repository

**Pull request merged**
