### PR TITLE
Use new OS.Xen API for grants

### PR DESCRIPTION
**Pull request by talex5**
See https://github.com/mirage/mirage-xen/pull/9

/cc @yomimono

### CODE REVIEW

**Comment by yomimono** [comment]
Thanks, this looks reasonable.  Are you still interested in having this go into a 1.9 branch (presumably for maintenance release) given that mirage-nat 1.1.0 is released and the current qubes-mirage-firewall HEAD uses the 2.0 API?

**Comment by talex5** [comment]
I'm happy to see this PR replaced by a rebased version.

**Comment by avsm** [comment]
This looks sensible to me as well.  I've got half-a-tree with a renaming of `OS.Xen` to `Mirage_xen`, so I'll save that until after these are merged and released.

**Comment by yomimono** [comment]
Rebase over at #85. If you like it, please merge it :)

**Comment by talex5** [comment]
Closing in favour of #85.

**Pull request closed without merging**
