### PR TITLE
Reflect mirage-xen api change

### PR DESCRIPTION
**Pull request by TheLortex**
The PR that breaks API is the following: mirage/mirage-xen#16

### CODE REVIEW

**Comment by talex5** [comment]
Note: I believe the plan was that Netchannel shouldn't be Xen-specific (despite the repository name and the fact that it's only used on Xen at the moment). In particular, it would be nice to be able to run tests on Unix. It seems a shame to move to platform-specific naming.

**Comment by avsm** [comment]
But don't the Unix tests still use the userspace Xen devices?  Netchannel seems very xen-specific in any practical sense, unless I'm missing something...

**Comment by talex5** [comment]
I might be confused about what `Os_xen` is then. I was assuming that e.g. `Os_xen.Xen` is the interface to the Xen hypervisor provided by the mirage-xen backend, and that there would be another `Os_unix.Xen` for the user-space stuff. Or will mirage-xen and mirage-unix both provide `Os_xen.Xen`? That would be fine, although the name seems a bit redundant in that case.

**Comment by TheLortex** [comment]
My goal was to separate common modules and Xen-specific modules in https://github.com/mirage/mirage-xen/blob/master/lib/oS.mli
To do that I simply wrapped all Xen-specific modules (including `Xen`) in an `Os_xen` module.

I'm not very familiar with `mirage-xen`, so are you saying that in `oS.mli` there are modules that are meant to be run on unix ?

**Pull request merged**
