### PR TITLE
Wait for the backend to enter the connected state

### LINKED ISSUE #20: Possible race condition on startup
Got the following trace in synjitsu, where the initial ARP packet and the first SYNACK seems to somehow overlap, resulting in the SYNACK (`id=2`) never actually sent on the network.

```
ARP: sending gratuitous from 192.168.2.140
Netif.writev
Netif.writev_no_retry
Netif.write_already_locked
Netif.write_request id=1 available-devices: [0])
Netif.Share_page_pool.use
Netif.Shared_page_pool.alloc
Netif.write_request: id=1 len=42 size=42
Netif.notify
Netfi.write_already_locked: Front.push done
Manager: configuration done
FAST-START mode. Watching xenstore for incoming SYN!
Ports: 80
Dest-ip: 192.168.2.1
Dest-ports: 58195
Found 1 started connections.
tx=65535 sequence=-19772235 options=(SACK_ok(Timestamp 2112076375 0)Noop Noop(Window_size_shift 5)Noop(MSS 1460)) tx_isn=452894287 rx_wnd=65535 rx_wnd_sca=2
Found SYN cookies.
Segment.output time=0.17 xmit=true rexmit=true
Wire.xmit checksum=14b7 192.168.2.140.80->192.168.2.1.58195 rst=false syn=true fin=false psh=false seq=452894287 ack=4275195062 options=[ MSS=1460; Window>>2 ] datalen=0 datafrag=0 dataoff=7 olen=8
Netif.writev
Netif.writev_no_retry
Netif.write_already_locked
Netif.write_request id=2 available-devices: [0])
Netif.Share_page_pool.use
Netif.write_request: id=2 len=62 size=62
Netfi.write_already_locked: Front.push done
Netfif.poll_thread:loop
Netif.rx_poll
Netif.refill_requests
Netif.tx_poll
Netif.write_request: id=2 Lwt_ring.Front.write done!
Netif.Shared_page_pool.put
Netif.write_request: id=1 Lwt_ring.Front.write done!
Netif.Shared_page_pool.put
Netfif.poll_thread:loop
Netif.rx_poll
Netif.refill_requests
Netif.tx_poll
Netfif.poll_thread:loop
Netif.rx_poll
Netif.refill_requests
Netif.tx_poll
Netfif.poll_thread:loop
....
```

### PR DESCRIPTION
**Pull request by djs55**
Previously we jumped straight into the connected state, read the backend
features and started transmitting packets and events. Some backends
(including at least the Linux netback) are not prepared to receive anything
before they have also transitioned into the connected state.

I believe this fixes #20

There is a chance that this doesn't actually fix the issue but simply masks
it with additional delay. However: (i) the delay seems very short; and
(ii) this is the right thing to do anyway.

Signed-off-by: David Scott <dave.scott@citrix.com>

### CODE REVIEW

**Comment by djs55** [comment]
On the cubieboard I could reproduce the issue with @MagnusS's test case. I also observed that a sleep made the problem go away. With this patch the issue goes away without the sleep. The patch will cause a (very short) delay during device connect which could be masking the issue, but I don't think so: the state machine is supposed to be used like this (I believe) and the extra delay is very short and the test is working very reliably for me know (where 10 runs == "very")

**Comment by avsm** [comment]
On inspection this is the right thing to do with respect to the Xen device protocol. Good catch!

**Comment by avsm** [comment]
Tested and running on live openmirage.org

**Comment by samoht** [comment]
yay!

**Comment by MagnusS** [comment]
great!

**Pull request merged**
