### PR TITLE
Fix wait_for_free_tx when ring is full

### PR DESCRIPTION
**Pull request by talex5**
Previously:

1. We waited even if the ring had enough free space (if `n >= numfree`).
2. We checked again as soon as the underlying event channel got an event. However, space doesn't become available in the ring until `tx_poll` processes the responses, which usually happens after that.

The effect of this is that large transfers would often hang or pause (pinging the unikernel would unstick it).

This change depends on https://github.com/mirage/shared-memory-ring/pull/15

### CODE REVIEW

**Comment by avsm** [comment]
Looks correct to me.

**Comment by djs55** [comment]
Aha, good one. Good idea to add the waiting function to the ring code.

**Comment by djs55** [comment]
OK, the shared-memory-ring API is in 1.1.1 (I've added a temporary package to mirage/mirage-dev). Anyone object to merging this and releasing this too?

**Comment by avsm** [comment]
go ahead and release smr-1.1.1 to opam -- it's just an API addition so I see no harm in mainlining it.

**Comment by talex5** [comment]
Thanks @djs55 - so this fix can be merged now that smr-1.1.1 is out?

**Comment by djs55** [comment]
Let's do it!

**Pull request merged**
